### ISSUE TITLE
Buttons 6,7,8,9 are not shown

### ISSUE THREAD

**Issue by abuali129** [mi5hmash/LimebrellaSharp#10]
Hi
What is the problem?
![image](https://github.com/user-attachments/assets/ea2a5bcd-08b8-4df4-9a56-7993a69335a6)

**Comment by mi5hmash** [comment]
Hello, it looks like there is a problem with the application scaling incorrectly.
What resolution and interface scaling do you have set in Windows?

**Comment by abuali129** [comment]
Yes, you were right, scaling is 300%.
I decreased it and it shows th buttons.

**Comment by mi5hmash** [comment]
I'm glad we identified the problem.
Also, If you want to unlock buttons (6) and (7) you have to enable SuperUser mode by triple-clicking the version number label (11).
