### ISSUE TITLE
How to find the SteamID of a save from internet?

### ISSUE THREAD

**Issue by SF-monkey** [mi5hmash/LimebrellaSharp#11]
I have a save downloaded from internet and it doesn't contain infomation about its original steamID. Is there a way to find it (with Hex editor or something) so I can use this tool?

**Comment by mi5hmash** [comment]
Hi, unfortunately I still haven't fixed a method responsible for bruteforcing SteamID.
You can try to put 411651526 or 0 as INPUT SteamID and See if any of them work. If not then I am afraid the only option is to locate the original file owner and ask him about its SteamID.
