### ISSUE TITLE
Operation is not supported on this platform.

### ISSUE THREAD

**Issue by Ebsbatalha** [mi5hmash/LimebrellaSharp#13]
Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

************** Texto de Exceção **************
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.Intrinsics.X86.Aes.KeygenAssist(Vector128`1 value, Byte control)
   at LimebrellaSharpCore.Helpers.LimeDeencryptor.AesKeygen(Span`1& aesRoundKeys, ReadOnlySpan`1 inputKey)
   at LimebrellaSharpCore.Helpers.LimeDeencryptor.Limetree(DsssLimeFile limeFile, UInt64 steamId, Boolean encrypt)
   at LimebrellaSharp.Form1.<>c__DisplayClass20_1.<ResignAll>b__1(Int64 ctr)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass20_0`1.<ForWorker64>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass20_0`1.<ForWorker64>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

************** Assemblies Carregados **************
System.Private.CoreLib
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Private.CoreLib.dll
----------------------------------------
LimebrellaSharp
    Versão do Assembly: 1.0.2.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Runtime
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57303
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.15/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57303
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.15/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.15/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 7.0.1523.57303
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.15/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Memory
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Memory.dll
----------------------------------------
System.Numerics.Vectors
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.15/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.ComponentModel.dll
----------------------------------------
System.Runtime.Loader
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57303
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.15/pt-BR/System.Windows.Forms.resources.dll
----------------------------------------
System.Resources.Extensions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.15/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57303
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.15/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.ObjectModel.dll
----------------------------------------
System.Linq
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Linq.dll
----------------------------------------
System.Collections.NonGeneric
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Collections.NonGeneric.dll
----------------------------------------
System.Text.RegularExpressions
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Text.RegularExpressions.dll
----------------------------------------
System.Threading.Tasks.Parallel
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Threading.Tasks.Parallel.dll
----------------------------------------
LimebrellaSharpCore
    Versão do Assembly: 1.0.0.0
    Versão do Win32: n/a
    Base de Código: 
----------------------------------------
System.Threading.ThreadPool
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Threading.ThreadPool.dll
----------------------------------------
System.Diagnostics.Tracing
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Diagnostics.Tracing.dll
----------------------------------------
System.Runtime.Intrinsics
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Runtime.Intrinsics.dll
----------------------------------------
System.Private.Uri
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Private.Uri.dll
----------------------------------------
System.Diagnostics.StackTrace
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Versão do Assembly: 7.0.0.0
    Versão do Win32: 7.0.1523.57226
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.15/System.Collections.Immutable.dll
----------------------------------------

************** Depuração JIT **************

**Comment by mi5hmash** [comment]
Some older CPU's (in this case: Intel Celeron J1900) do not support some low-level instructions (in this case: System.Runtime.Intrinsics.X86.Aes.KeygenAssist) that I used in my code. For now I do not have any solution, but I will try to implement the pure software alternative in the next version using standard bitwise and logical operations.

**Comment by mi5hmash** [comment]
Added software-based alternatives for intrinsics in v2.0.0.
