### ISSUE TITLE
RE4 Unable to recognize the converted game save

### ISSUE THREAD

**Issue by x-kang** [mi5hmash/LimebrellaSharp#3]
Hi!
When I use your tool to convert my old steam account saves, fully following the steps of unpack,resign, pac, and then copy the new game save to the folder of another new account, and then I open the game , I am prompted that “unable to load save data”. Is there anything wrong with my steps?

**Comment by mi5hmash** [comment]
Hi!
You can send me your save files and note containing both SteamIDs so I can examine them. 
You can upload them to my Dropbox [here](https://www.dropbox.com/request/y9xOWd8uWuio6NNl5giI).

**Comment by x-kang** [comment]
I have already uploaded save files to your Dropbox, ID 1523107836 is the original steam account save files, and ID 1528414544 is the new steam account save files converted by your tool. Thank you very much for your help in analyzing the cause of the problem.

**Comment by mi5hmash** [comment]
Okay, so I've converted your save files with LimebrellaSharp and tried to load them. The game's been loaded in Chinese. At first, I had the “unable to load save data” problem raised by "data002Slot.bin". I've identified which file was it by searching for a gap between two elements of the in-game "Load Game" menu list.
**data00-1.bin** - Profile
**data000.bin** - AutoSave
**data00XSlot.bin** - where X stands for a slot number
To fix it I had to load up any other save and use the typewriter to create a save data on each slot that was "corrupted", quit the game, and paste the converted saves again into the "...\2050650\remote\win64_save" directory.
I understand that you couldn't load any saved data. Steam Cloud may be the issue. Try to turn it off for the RE4 or disconnect your PC from the Internet. Next, delete the content of "...\1528414544\2050650\remote\win64_save", paste the converted saves into that directory, and try to load them from the game menu while being offline.

**Comment by mi5hmash** [comment]
@x-kang 
After you test it, please let me know.

**Comment by mi5hmash** [comment]
I've updated my tool which should solve your problem. 
I'll leave this topic open for a while in case you would like to post a comment.

**Comment by x-kang** [comment]
Sorry for not getting back to you sooner. I've been pretty busy with work lately. I tested the game saves file you provided today and unfortunately, the RE4 game programe would crash every time when loading saves. I've tried a lot of things, including deleting the entire 2050650 folder (RE4 Steam game ID), and reinitializing the game and pasting the converted save files , but it still crashes when loading the saves.（My English is not very good, so I used AI translation. I hope it didn't cause any trouble for you.）

**Comment by mi5hmash** [comment]
No worries, I can understand what you write. Unfortunately, this is the only way, because I do not speak Chinese.
I've tested it one more time and taken a bunch of screenshots during the process.
I resigned the first four saves with the latest version of LimebrellaSharp (v1.0.2).
Please, download the [ShawnKang_2.zip](https://www.dropbox.com/scl/fo/o6csi39zxf75wvughkb8k/h?rlkey=n56f830cgh80ywd18y8psnjng&dl=0), unpack it, and follow the images.
Skip image number 4 (4.png), because I have included it only to show you what settings I have used during the conversion.
The files in the archive are already signed with your new SteamID (1528414544).

**Comment by mi5hmash** [comment]
- Unpack = Decrypt files from Input Folder using the left steam32_ID;
- Pack = Encrypt from Input Folder using the right steam32_ID;
- Resign = Unpack + Pack;

That's really weird. I wish it has worked for you. The last thing you could try is to start a new game, rush to the first typewriter, save the game, overwrite "data000.bin" with the one from the [ShawnKang_2.zip](https://www.dropbox.com/scl/fo/o6csi39zxf75wvughkb8k/h?rlkey=n56f830cgh80ywd18y8psnjng&dl=0) archive, close the game, run it again and try to load AutoSave (it should load you into chapter 9 where you left earlier). This is my last idea. Sorry, I couldn't be more helpful.
