### ISSUE TITLE
[OFF-TOPIC] Question about AutoStrong Encryption

### ISSUE THREAD

**Issue by Hepi34** [mi5hmash/LimebrellaSharp#4]
I was reading your posts in the fearless cheatengine forum, and you shortly mentioned that re7 and re8 use AutoStrong Encription. In the past, I already tried to decrypt save files from re7 and 8. Did you make any progress on autostrong decryption or did you focus on Lime?

**Comment by mi5hmash** [comment]
Hi [Hepi34](https://github.com/Hepi34).
I found a way to bypass the SteamID check and that was exactly what I was trying to achieve back then, so I have lost interest in further analyzing the AutoStrong Encryption. Then I focused on Lime and other projects.
How did your tries go?

**Comment by Hepi34** [comment]
@mi5hmash I was looking at the re7.exe with x64dbg. I hoped to see a point where the exe calls the save files or uses an encryption/decrytpion key. I couldn't find something like that, but I've been trying again every now and then.

If you don't mind, could you tell me dow exactly you bypassed the StemID check? Since I'd really it if I could finally use my re7 and re8 saves on the legit version.

**Comment by mi5hmash** [comment]
@Hepi34 
RE 7 - [CheatEngineTable](https://mega.nz/folder/djBVmYCK#E07_9anwVIkYf6Uo0MVCAQ)
RE 8 - soon

1. Copy save data into _"Steam\userdata\<your_steamid_32>\418370\remote\win64_save"_ folder.
2. Open the CE Table before launching the game, check **[ACTIVATE ME]** and **DISABLE USER_ID CHECK**
3. Run the game and enjoy.

**Comment by Hepi34** [comment]
Thank you so much, this is exactly what I've been looking for! I'll look into how this works and maybe I'll be able to make an RE8 version.

**Comment by mi5hmash** [comment]
@Hepi34
I have uploaded both tables.
The first one for RE7 had a bug that did not activate the script after the game is launched, but I fixed it and reuploaded it.

**Comment by Hepi34** [comment]
@mi5hmash Thank you so much, I really appreciate it!
