### ISSUE TITLE
Unable to Resign files (Re4)

### ISSUE THREAD

**Issue by inasense** [mi5hmash/LimebrellaSharp#7]
Hi there, awesome tool you made here. Unfortunately I'm running into an issue where after filling the folder path and text boxes with relevant information and hitting Resign all the progress bar completes but shows Number of processed files: 0 obviously yielding no resigned files in the output folder. Any helps is hugely appreciated. Thanks.

**Comment by mi5hmash** [comment]
Hi, 
the tool skips the files that it can't recognize or when the user provides an invalid Steam ID (INPUT).
If you're sure that you are using a proper Steam ID then you may zip one or two of these files and send them to me so I can check if the FILE HEADER and FILE FOOTER are correct. Please, keep in mind that I'm not able to bruteforce the Steam ID of the original holder so I can't help you with that.

**Comment by inasense** [comment]
Thanks for your response. I got them to resign, so the original issue can be closed/edited, but unfortunately my steam game nor my cracked copy recognize them now. I'm truly at a loss for how this happened, but if you have any ideas/advice I'd hugely appreciate it.

**Comment by mi5hmash** [comment]
Have you tried to start a new game, reach the first typewriter machine, make a save on each available slot, close the game, and finally replace the files with the ones you already resigned?

**Comment by inasense** [comment]
After walking through the steps a few more times I was finally able to transfer the save files successfully. Wouldn't have been possible without your tool @mi5hmash thank you.

**Comment by mi5hmash** [comment]
Glad to hear that my research has helped you dealt with the problem. Have a great time!
