### ISSUE TITLE
Will this tool support RE7 in the future?

### ISSUE THREAD

**Issue by GHBanYan** [mi5hmash/LimebrellaSharp#9]

**Comment by mi5hmash** [comment]
This tool won't support RE7, because it use other encryption metod. For RE2, RE3, RE7, RE8 you can use [AutostongSharp](https://github.com/mi5hmash/AutostrongSharp).

**Comment by GHBanYan** [comment]
> This tool won't support RE7, because it uses other encryption method. For RE2, RE3, RE7, RE8 you can use [AutostongSharp](https://github.com/mi5hmash/AutostrongSharp).

thanks!
